package me.molybdenum.ambience_mini.engine.client.configuration.syntactic_analysis;

import me.molybdenum.ambience_mini.engine.client.configuration.abstract_syntax.expression.*;
import me.molybdenum.ambience_mini.engine.client.configuration.abstract_syntax.config.*;
import me.molybdenum.ambience_mini.engine.client.configuration.abstract_syntax.schedule.*;
import me.molybdenum.ambience_mini.engine.client.configuration.abstract_syntax.playlist.*;
import me.molybdenum.ambience_mini.engine.client.configuration.abstract_syntax.type.*;
import me.molybdenum.ambience_mini.engine.client.configuration.errors.LoadError;
import me.molybdenum.ambience_mini.engine.client.configuration.errors.SynError;

import java.io.InputStream;
import java.util.ArrayList;

/* The required start of a Coco/R grammar file. "Program" specifies the starting symbol of the grammar. */


public class Parser {
	public static final int _EOF = 0;
	public static final int _IDENT = 1;
	public static final int _INT = 2;
	public static final int _FLOAT = 3;
	public static final int _STRING = 4;
	public static final int maxT = 52;

	static final boolean _T = true;
	static final boolean _x = false;
	static final int minErrDist = 2;

	Token t;    // last recognized token
	Token la;   // lookahead token
	int errDist = minErrDist;

	Scanner scanner;
	Errors errors;

	Config mainNode = null; // This contains the AST generated by calling parser.Parse().

    private static String removeFirstAndLast(String str) {
        return str.substring(1, str.length() - 1);
    }

/*------------------------------------------------------------------------*/
/* The following section contains the token specification of Dims.*/


	public Parser() { }

	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) {
				++errDist;
				break;
			}

			la = t;
		}
	}

	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}

	boolean StartOf (int s) {
		return set[s][la.kind];
	}

	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}

	boolean WeakSeparator (int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) { Get(); return true; }
		else if (StartOf(repFol)) return false;
		else {
			SynErr(n);
			while (!(set[syFol][kind] || set[repFol][kind] || set[0][kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}

	void File() {
		mainNode = Conf();
	}

	Config  Conf() {
		Config  conf;
		conf = null; 
		if (la.kind == 5) {
			Get();
			Expect(1);
			IdentP ident = new IdentP(t.val, t.line); 
			Expect(6);
			Playlist play = Play();
			Expect(7);
			Config inner = Conf();
			conf = new PlaylistDecl(ident, play, inner); 
		} else if (StartOf(1)) {
			Schedule schedule = Shed();
			conf = new ScheduleDecl(schedule); 
		} else SynErr(53);
		return conf;
	}

	Playlist  Play() {
		Playlist  play;
		play = PlayTerm();
		while (la.kind == 8) {
			Get();
			Playlist play2 = PlayTerm();
			play = new Concat(play, play2); 
		}
		return play;
	}

	Schedule  Shed() {
		Schedule  schedule;
		schedule = null; boolean instant = false; 
		switch (la.kind) {
		case 15: {
			Get();
			if (la.kind == 16) {
				Get();
				instant = true; 
			}
			Playlist pl = Play();
			Expect(7);
			schedule = new Play(pl, instant); 
			break;
		}
		case 17: {
			Get();
			ArrayList<Schedule> items = new ArrayList<>();  
			while (StartOf(1)) {
				Schedule schedule2 = Shed();
				items.add(schedule2); 
			}
			Expect(18);
			schedule = new Block(items); 
			break;
		}
		case 19: {
			Get();
			int line = t.line; 
			Expect(20);
			Expr expr = Expr();
			Expect(21);
			Schedule schedule2 = Shed();
			schedule = new When(expr, schedule2, line); 
			break;
		}
		case 22: {
			Get();
			int line = t.line; Type type = null; 
			Expect(1);
			IdentE ident = new IdentE(t.val, t.line); 
			if (la.kind == 23) {
				Get();
				type = Type();
			}
			Expect(6);
			Expr expr = Expr();
			Expect(24);
			Schedule shed = Shed();
			schedule = new Let(type, ident, expr, shed, line); 
			break;
		}
		case 25: {
			Get();
			int line = t.line; 
			Schedule schedule2 = Shed();
			schedule = new When(new BoolLit(true), schedule2, line); 
			break;
		}
		case 26: {
			Get();
			int line = t.line; 
			Schedule schedule2 = Shed();
			schedule = new Interrupt(schedule2, line); 
			break;
		}
		default: SynErr(54); break;
		}
		return schedule;
	}

	Playlist  PlayTerm() {
		Playlist  play;
		play = new Nil(); FloatLit gain = null; 
		if (la.kind == 9) {
			Get();
			if (StartOf(2)) {
				Playlist load = PlayTerm();
				play = load;      
				while (la.kind == 10) {
					Get();
					load = PlayTerm();
					play = new Concat(play, load); 
				}
			}
			Expect(11);
		} else if (la.kind == 1) {
			Get();
			play = new IdentP(t.val, t.line); 
		} else if (la.kind == 12) {
			Get();
		} else if (la.kind == 4) {
			Get();
			StringLit file = new StringLit(removeFirstAndLast(t.val)); int line = t.line; 
			if (la.kind == 13) {
				Get();
				if (la.kind == 3) {
					Get();
				} else if (la.kind == 2) {
					Get();
				} else SynErr(55);
				gain = new FloatLit(Float.parseFloat(t.val));            
				Expect(14);
			}
			play = new Load(file, gain, line);                           
		} else SynErr(56);
		return play;
	}

	Expr  Expr() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprEq();
		while (la.kind == 27 || la.kind == 28) {
			if (la.kind == 27) {
				Get();
				op = BinaryOperators.AND; line = t.line; 
			} else {
				Get();
				op = BinaryOperators.OR; line = t.line; 
			}
			Expr expr2 = ExprEq();
			expr = new BinaryOp(op, expr, expr2, line); 
		}
		return expr;
	}

	Type  Type() {
		Type  type;
		type = null; 
		switch (la.kind) {
		case 46: {
			Get();
			type = BoolT.INSTANCE; 
			break;
		}
		case 47: {
			Get();
			type = IntT.INSTANCE; 
			break;
		}
		case 48: {
			Get();
			type = FloatT.INSTANCE; 
			break;
		}
		case 49: {
			Get();
			type = StringT.INSTANCE; 
			break;
		}
		case 50: {
			Get();
			type = AreaT.INSTANCE; 
			break;
		}
		case 5: {
			Get();
			type = PlaylistT.INSTANCE; 
			break;
		}
		case 51: {
			Get();
			Expect(13);
			Type elemType = Type();
			Expect(14);
			type = new ListT(elemType); 
			break;
		}
		default: SynErr(57); break;
		}
		return type;
	}

	Expr  ExprEq() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprRel();
		while (StartOf(3)) {
			if (la.kind == 29 || la.kind == 30 || la.kind == 31) {
				if (la.kind == 29) {
					Get();
					op = BinaryOperators.EQ; line = t.line; 
				} else if (la.kind == 30) {
					Get();
					op = BinaryOperators.APP_EQ; line = t.line; 
				} else {
					Get();
					op = BinaryOperators.MATCH; line = t.line; 
				}
				Expr expr2 = ExprRel();
				expr = new BinaryOp(op, expr, expr2, line); 
			} else {
				Get();
				line = t.line; 
				Expr expr2 = ExprRel();
				expr = new UnaryOp(UnaryOperators.NOT, new BinaryOp(BinaryOperators.EQ, expr, expr2, line), line); 
			}
		}
		return expr;
	}

	Expr  ExprRel() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprPre();
		while (StartOf(4)) {
			if (la.kind == 13) {
				Get();
				line = t.line; 
				Expr expr2 = ExprPre();
				expr = new BinaryOp(BinaryOperators.LT, expr, expr2, line); 
			} else if (la.kind == 14) {
				Get();
				line = t.line; 
				Expr expr2 = ExprPre();
				expr = new BinaryOp(BinaryOperators.LT, expr2, expr, line); 
			} else if (la.kind == 33) {
				Get();
				line = t.line; 
				Expr expr2 = ExprPre();
				expr = new BinaryOp(BinaryOperators.LE, expr, expr2, line); 
			} else {
				Get();
				line = t.line; 
				Expr expr2 = ExprPre();
				expr = new BinaryOp(BinaryOperators.LE, expr2, expr, line); 
			}
		}
		return expr;
	}

	Expr  ExprPre() {
		Expr  expr;
		expr = null; UnaryOperators op; int line; 
		if (la.kind == 35 || la.kind == 36) {
			if (la.kind == 35) {
				Get();
				op = UnaryOperators.NOT; 
			} else {
				Get();
				op = UnaryOperators.NEG; 
			}
			line = t.line; 
			expr = ExprPre();
			expr = new UnaryOp(op, expr, line); 
		} else if (StartOf(5)) {
			expr = ExprSuf();
		} else SynErr(58);
		return expr;
	}

	Expr  ExprSuf() {
		Expr  expr;
		expr = ExprTerm();
		while (la.kind == 9 || la.kind == 37) {
			if (la.kind == 9) {
				Get();
				int line = t.line; 
				Expr index = Expr();
				Expect(11);
				expr = new BinaryOp(BinaryOperators.INDEXER, expr, index, line); 
			} else {
				Get();
				int line = t.line; 
				Expect(1);
				expr = new Accessor(expr, new IdentE(t.val, t.line), line); 
			}
		}
		return expr;
	}

	Expr  ExprTerm() {
		Expr  expr;
		expr = null; Quantifiers quantifier = Quantifiers.ANY; 
		switch (la.kind) {
		case 1: {
			Get();
			expr = new IdentE(t.val, t.line);                      
			break;
		}
		case 2: {
			Get();
			expr = new IntLit(Integer.parseInt(t.val));      
			break;
		}
		case 3: {
			Get();
			expr = new FloatLit(Float.parseFloat(t.val));    
			break;
		}
		case 4: {
			Get();
			expr = new StringLit(removeFirstAndLast(t.val)); 
			break;
		}
		case 38: {
			Get();
			expr = new BoolLit(true);                        
			break;
		}
		case 39: {
			Get();
			expr = new BoolLit(false);                       
			break;
		}
		case 40: {
			Get();
			expr = new UndefinedLit(); 
			break;
		}
		case 41: {
			Get();
			Expect(1);
			expr = new GetEvent(new IdentE(t.val, t.line));    
			break;
		}
		case 42: {
			Get();
			Expect(1);
			expr = new GetProperty(new IdentE(t.val, t.line)); 
			break;
		}
		case 43: case 44: {
			if (la.kind == 43) {
				Get();
			} else {
				Get();
				quantifier = Quantifiers.ALL; 
			}
			Expect(1);
			String identifier = t.val; int line = t.line; 
			Expect(24);
			int inLine = t.line; 
			Expr list = Expr();
			Expect(45);
			int whereLine = t.line; 
			Expr cond = Expr();
			Expect(18);
			expr = new QuantifierOp(quantifier, new IdentE(identifier, line), list, cond, inLine, whereLine); 
			break;
		}
		case 20: {
			Get();
			expr = Expr();
			Expect(21);
			break;
		}
		default: SynErr(59); break;
		}
		return expr;
	}



	public Config Parse(InputStream inputStream, ArrayList<LoadError> errors) {
		this.scanner = new Scanner(inputStream);
		this.errors = new Errors(errors);

		la = new Token();
		la.val = "";
		Get();
		File();
		Expect(0);

		scanner.buffer.Close();
		return mainNode;
	}

	private static final boolean[][] set = {
		{_T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_T, _x,_T,_x,_T, _x,_x,_T,_x, _x,_T,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_T,_x,_x, _T,_x,_x,_x, _x,_T,_x,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_T,_T, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_T,_T,_T, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _T,_T,_T,_T, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x}

	};
} // end Parser

class Errors {
	ArrayList<LoadError> errors;

    public Errors(ArrayList<LoadError> errors) {
        this.errors = errors;
    }

	public void SynErr (int line, int col, int n) {
        String s;
        switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "IDENT expected"; break;
			case 2: s = "INT expected"; break;
			case 3: s = "FLOAT expected"; break;
			case 4: s = "STRING expected"; break;
			case 5: s = "\"playlist\" expected"; break;
			case 6: s = "\"=\" expected"; break;
			case 7: s = "\";\" expected"; break;
			case 8: s = "\"++\" expected"; break;
			case 9: s = "\"[\" expected"; break;
			case 10: s = "\",\" expected"; break;
			case 11: s = "\"]\" expected"; break;
			case 12: s = "\"NIL\" expected"; break;
			case 13: s = "\"<\" expected"; break;
			case 14: s = "\">\" expected"; break;
			case 15: s = "\"play\" expected"; break;
			case 16: s = "\"instant\" expected"; break;
			case 17: s = "\"begin\" expected"; break;
			case 18: s = "\"end\" expected"; break;
			case 19: s = "\"when\" expected"; break;
			case 20: s = "\"(\" expected"; break;
			case 21: s = "\")\" expected"; break;
			case 22: s = "\"let\" expected"; break;
			case 23: s = "\":\" expected"; break;
			case 24: s = "\"in\" expected"; break;
			case 25: s = "\"default\" expected"; break;
			case 26: s = "\"interrupt\" expected"; break;
			case 27: s = "\"&&\" expected"; break;
			case 28: s = "\"||\" expected"; break;
			case 29: s = "\"==\" expected"; break;
			case 30: s = "\"~~\" expected"; break;
			case 31: s = "\"*~\" expected"; break;
			case 32: s = "\"!=\" expected"; break;
			case 33: s = "\"<=\" expected"; break;
			case 34: s = "\">=\" expected"; break;
			case 35: s = "\"!\" expected"; break;
			case 36: s = "\"-\" expected"; break;
			case 37: s = "\".\" expected"; break;
			case 38: s = "\"true\" expected"; break;
			case 39: s = "\"false\" expected"; break;
			case 40: s = "\"undefined\" expected"; break;
			case 41: s = "\"@\" expected"; break;
			case 42: s = "\"$\" expected"; break;
			case 43: s = "\"any\" expected"; break;
			case 44: s = "\"all\" expected"; break;
			case 45: s = "\"has\" expected"; break;
			case 46: s = "\"bool\" expected"; break;
			case 47: s = "\"int\" expected"; break;
			case 48: s = "\"float\" expected"; break;
			case 49: s = "\"string\" expected"; break;
			case 50: s = "\"area\" expected"; break;
			case 51: s = "\"list\" expected"; break;
			case 52: s = "??? expected"; break;
			case 53: s = "invalid Conf"; break;
			case 54: s = "invalid Shed"; break;
			case 55: s = "invalid PlayTerm"; break;
			case 56: s = "invalid PlayTerm"; break;
			case 57: s = "invalid Type"; break;
			case 58: s = "invalid ExprPre"; break;
			case 59: s = "invalid ExprTerm"; break;
            default: s = "error " + n; break;
        }
        errors.add(new SynError(line, col, s));
    }
} // Errors
