package me.molybdenum.ambience_mini.engine.shared.configuration.syntactic_analysis;

import me.molybdenum.ambience_mini.engine.shared.configuration.abstract_syntax.expression.*;
import me.molybdenum.ambience_mini.engine.shared.configuration.abstract_syntax.schedule.*;
import me.molybdenum.ambience_mini.engine.shared.configuration.abstract_syntax.server_playlists.*;
import me.molybdenum.ambience_mini.engine.shared.configuration.abstract_syntax.type.*;
import me.molybdenum.ambience_mini.engine.shared.configuration.abstract_syntax.misc.*;
import me.molybdenum.ambience_mini.engine.shared.configuration.abstract_syntax.*;
import me.molybdenum.ambience_mini.engine.shared.configuration.messages.Message;
import me.molybdenum.ambience_mini.engine.shared.configuration.messages.SynError;

import java.io.InputStream;
import java.util.ArrayList;
import java.util.HashMap;

/* The required start of a Coco/R grammar file. "Program" specifies the starting symbol of the grammar. */


public class Parser {
	public static final int _EOF = 0;
	public static final int _IDENT = 1;
	public static final int _INT = 2;
	public static final int _FLOAT = 3;
	public static final int _STRING = 4;
	public static final int maxT = 61;

	static final boolean _T = true;
	static final boolean _x = false;
	static final int minErrDist = 2;

	Token t;    // last recognized token
	Token la;   // lookahead token
	int errDist = minErrDist;

	Scanner scanner;
	Errors errors;

	Config mainNode = null; // This contains the AST generated by calling parser.Parse().

    private static String removeFirstAndLast(String str) {
        return str.substring(1, str.length() - 1);
    }

    private boolean isSecondLookaheadNumber() {
        Token la2 = scanner.Peek();
        return la2.kind == _INT || la2.kind == _FLOAT;
    }

/*------------------------------------------------------------------------*/
/* The following section contains the token specification of Dims.*/


	public Parser() { }

	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) {
				++errDist;
				break;
			}

			la = t;
		}
	}

	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}

	boolean StartOf (int s) {
		return set[s][la.kind];
	}

	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}

	boolean WeakSeparator (int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) { Get(); return true; }
		else if (StartOf(repFol)) return false;
		else {
			SynErr(n);
			while (!(set[syFol][kind] || set[repFol][kind] || set[0][kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}

	void File() {
		mainNode = Conf();
	}

	Config  Conf() {
		Config  conf;
		var declarations = new ArrayList<GlobalDecl>(); ServerPlaylists serverPl = null; Schedule schedule = null; 
		while (StartOf(1)) {
			GlobalDecl decl = Decl();
			declarations.add(decl); 
		}
		if (la.kind == 5) {
			Get();
			Expect(6);
			serverPl = ServerPlaylists();
		}
		if (StartOf(2)) {
			schedule = Shed();
		}
		conf = new Config(declarations, serverPl, schedule); 
		return conf;
	}

	GlobalDecl  Decl() {
		GlobalDecl  decl;
		Type type = Type();
		Expect(1);
		Ident ident = new Ident(t.val, t.line); 
		Expect(7);
		Expr expr = Expr();
		Expect(8);
		decl = new GlobalDecl(type, ident, expr); 
		return decl;
	}

	ServerPlaylists  ServerPlaylists() {
		ServerPlaylists  serverPl;
		serverPl = null; 
		if (StartOf(3)) {
			Expr expr = Expr();
			Expect(8);
			serverPl = new PlaylistInstance(expr); 
		} else if (la.kind == 9) {
			Get();
			HashMap<String, ServerPlaylists> groups = new HashMap<>(); 
			while (la.kind == 4) {
				Get();
				String groupName = removeFirstAndLast(t.val); 
				Expect(6);
				ServerPlaylists serverPl2 = ServerPlaylists();
				groups.put(groupName, serverPl2); 
			}
			Expect(10);
			serverPl = new PlaylistGroup(groups); 
		} else SynErr(62);
		return serverPl;
	}

	Schedule  Shed() {
		Schedule  schedule;
		schedule = null; boolean instant = false; boolean ifdef = false; 
		switch (la.kind) {
		case 11: {
			Get();
			int line = t.line; 
			while (la.kind == 12 || la.kind == 13) {
				if (la.kind == 12) {
					Get();
					instant = true; 
				} else {
					Get();
					ifdef = true; 
				}
			}
			Expr expr = Expr();
			IntLit priority = null; 
			if (la.kind == 14) {
				Get();
				Expect(2);
				priority = new IntLit(Integer.parseInt(t.val), t.line); 
			}
			Expect(8);
			schedule = new Play(expr, instant, ifdef, priority, line); 
			break;
		}
		case 15: {
			Get();
			int line = t.line; 
			Expect(8);
			schedule = new Vanilla(line); 
			break;
		}
		case 16: {
			Get();
			ArrayList<Schedule> body = new ArrayList<>(); int line = t.line; 
			while (StartOf(2)) {
				Schedule schedule2 = Shed();
				body.add(schedule2); 
			}
			Expect(10);
			schedule = new Block(body, line); 
			break;
		}
		case 17: {
			Get();
			int line = t.line; 
			Expect(18);
			Expr expr = Expr();
			Expect(19);
			Schedule schedule2 = Shed();
			schedule = new When(expr, schedule2, line); 
			break;
		}
		case 20: {
			Get();
			int line = t.line; Type type = null; 
			Expect(1);
			Ident ident = new Ident(t.val, t.line); 
			if (la.kind == 6) {
				Get();
				type = Type();
			}
			Expect(7);
			Expr expr = Expr();
			Expect(21);
			Schedule shed = Shed();
			schedule = new Let(type, ident, expr, shed, line); 
			break;
		}
		case 22: {
			Get();
			schedule = Shed();
			break;
		}
		case 23: {
			Get();
			int line = t.line; 
			Schedule schedule2 = Shed();
			schedule = new Interrupt(schedule2, line); 
			break;
		}
		default: SynErr(63); break;
		}
		return schedule;
	}

	Type  Type() {
		Type  type;
		type = null; 
		switch (la.kind) {
		case 52: {
			Get();
			type = BoolT.INSTANCE; 
			break;
		}
		case 53: {
			Get();
			type = IntT.INSTANCE; 
			break;
		}
		case 54: {
			Get();
			type = FloatT.INSTANCE; 
			break;
		}
		case 55: {
			Get();
			type = StringT.INSTANCE; 
			break;
		}
		case 56: {
			Get();
			type = AreaT.INSTANCE; 
			break;
		}
		case 57: {
			Get();
			type = CombatantT.INSTANCE; 
			break;
		}
		case 58: {
			Get();
			type = PlaylistT.INSTANCE; 
			break;
		}
		case 59: {
			Get();
			Expect(30);
			Type elemType = Type();
			Expect(31);
			type = new ListT(elemType); 
			break;
		}
		case 60: {
			Get();
			Expect(30);
			Type elemType1 = Type();
			Expect(48);
			Type elemType2 = Type();
			Expect(31);
			type = new MapT(elemType1, elemType2); 
			break;
		}
		default: SynErr(64); break;
		}
		return type;
	}

	Expr  Expr() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprEq();
		while (la.kind == 24 || la.kind == 25) {
			if (la.kind == 24) {
				Get();
				op = BinaryOperators.AND; line = t.line; 
			} else {
				Get();
				op = BinaryOperators.OR; line = t.line; 
			}
			Expr expr2 = ExprEq();
			expr = new BinaryOp(op, expr, expr2, line); 
		}
		return expr;
	}

	Expr  ExprEq() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprRel();
		while (StartOf(4)) {
			if (la.kind == 26 || la.kind == 27 || la.kind == 28) {
				if (la.kind == 26) {
					Get();
					op = BinaryOperators.EQ; line = t.line; 
				} else if (la.kind == 27) {
					Get();
					op = BinaryOperators.APP_EQ; line = t.line; 
				} else {
					Get();
					op = BinaryOperators.MATCH; line = t.line; 
				}
				Expr expr2 = ExprRel();
				expr = new BinaryOp(op, expr, expr2, line); 
			} else {
				Get();
				line = t.line; 
				Expr expr2 = ExprRel();
				expr = new UnaryOp(UnaryOperators.NOT, new BinaryOp(BinaryOperators.EQ, expr, expr2, line), line); 
			}
		}
		return expr;
	}

	Expr  ExprRel() {
		Expr  expr;
		int line = -1; 
		expr = ExprAdd();
		while (StartOf(5)) {
			if (la.kind == 30) {
				Get();
				line = t.line; 
				Expr expr2 = ExprAdd();
				expr = new BinaryOp(BinaryOperators.LT, expr, expr2, line); 
			} else if (la.kind == 31) {
				Get();
				line = t.line; 
				Expr expr2 = ExprAdd();
				expr = new BinaryOp(BinaryOperators.LT, expr2, expr, line); 
			} else if (la.kind == 32) {
				Get();
				line = t.line; 
				Expr expr2 = ExprAdd();
				expr = new BinaryOp(BinaryOperators.LE, expr, expr2, line); 
			} else {
				Get();
				line = t.line; 
				Expr expr2 = ExprAdd();
				expr = new BinaryOp(BinaryOperators.LE, expr2, expr, line); 
			}
		}
		return expr;
	}

	Expr  ExprAdd() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprMul();
		while (la.kind == 34 || la.kind == 35) {
			if (la.kind == 34) {
				Get();
				op = BinaryOperators.ADD; line = t.line; 
			} else {
				Get();
				op = BinaryOperators.SUB; line = t.line; 
			}
			Expr expr2 = ExprMul();
			expr = new BinaryOp(op, expr, expr2, line); 
		}
		return expr;
	}

	Expr  ExprMul() {
		Expr  expr;
		BinaryOperators op; int line = -1; 
		expr = ExprPre();
		while (la.kind == 36 || la.kind == 37 || la.kind == 38) {
			if (la.kind == 36) {
				Get();
				op = BinaryOperators.MUL; line = t.line; 
			} else if (la.kind == 37) {
				Get();
				op = BinaryOperators.DIV; line = t.line; 
			} else {
				Get();
				op = BinaryOperators.APPEND; line = t.line; 
			}
			Expr expr2 = ExprPre();
			expr = new BinaryOp(op, expr, expr2, line); 
		}
		return expr;
	}

	Expr  ExprPre() {
		Expr  expr;
		expr = null; UnaryOperators op; int line; 
		if (la.kind == 35 || la.kind == 39) {
			if (la.kind == 39) {
				Get();
				op = UnaryOperators.NOT; 
			} else {
				Get();
				op = UnaryOperators.NEG; 
			}
			line = t.line; 
			expr = ExprPre();
			expr = new UnaryOp(op, expr, line); 
		} else if (StartOf(6)) {
			expr = ExprSuf();
		} else SynErr(65);
		return expr;
	}

	Expr  ExprSuf() {
		Expr  expr;
		expr = ExprTerm();
		while (la.kind == 40 || la.kind == 42) {
			if (la.kind == 40) {
				Get();
				int line = t.line; 
				Expr index = Expr();
				Expect(41);
				expr = new BinaryOp(BinaryOperators.INDEXER, expr, index, line); 
			} else {
				Get();
				int line = t.line; 
				Expect(1);
				expr = new Accessor(expr, new Ident(t.val, t.line), line); 
			}
		}
		return expr;
	}

	Expr  ExprTerm() {
		Expr  expr;
		expr = null; Quantifiers quantifier = Quantifiers.ANY; 
		switch (la.kind) {
		case 1: {
			Get();
			expr = new Ident(t.val, t.line);                      
			break;
		}
		case 2: case 3: case 4: case 34: case 35: case 49: case 50: case 51: {
			expr = Const();
			break;
		}
		case 43: {
			Get();
			Expect(1);
			expr = new GetEvent(new Ident(t.val, t.line));    
			break;
		}
		case 44: {
			Get();
			Expect(1);
			expr = new GetProperty(new Ident(t.val, t.line)); 
			break;
		}
		case 45: case 46: {
			if (la.kind == 45) {
				Get();
			} else {
				Get();
				quantifier = Quantifiers.ALL; 
			}
			Expect(1);
			String identifier = t.val; int line = t.line; 
			Expect(21);
			int inLine = t.line; 
			Expr list = Expr();
			Expect(47);
			int whereLine = t.line; 
			Expr cond = Expr();
			Expect(10);
			expr = new QuantifierOp(quantifier, new Ident(identifier, line), list, cond, inLine, whereLine); 
			break;
		}
		case 18: {
			Get();
			expr = Expr();
			Expect(19);
			break;
		}
		case 40: {
			Get();
			expr = new PlaylistLit(t.line); 
			if (la.kind == 4) {
				PlaylistLit.Load load = Music();
				((PlaylistLit)expr).music().add(load); 
				while (la.kind == 48) {
					Get();
					load = Music();
					((PlaylistLit)expr).music().add(load); 
				}
			}
			Expect(41);
			break;
		}
		default: SynErr(66); break;
		}
		return expr;
	}

	Expr  Const() {
		Expr  expr;
		expr = null;                                             
		if (la.kind == 49) {
			Get();
			expr = new UndefinedLit(t.line);                         
		} else if (la.kind == 50) {
			Get();
			expr = new BoolLit(true, t.line);                        
		} else if (la.kind == 51) {
			Get();
			expr = new BoolLit(false, t.line);                       
		} else if (la.kind == 4) {
			Get();
			expr = new StringLit(removeFirstAndLast(t.val), t.line); 
		} else if (StartOf(7)) {
			expr = Num();
		} else SynErr(67);
		return expr;
	}

	PlaylistLit.Load  Music() {
		PlaylistLit.Load  load;
		Expect(4);
		StringLit file = new StringLit(removeFirstAndLast(t.val), t.line); int line = t.line; var args = new ArgList(); 
		if (la.kind == 30) {
			Get();
			MusicArgs(args);
			Expect(31);
		}
		load = new PlaylistLit.Load(file, args, line); 
		return load;
	}

	Expr  Num() {
		Expr  expr;
		expr = null; int sign = 1; 
		if (la.kind == 34 || la.kind == 35) {
			if (la.kind == 35) {
				Get();
				sign = -1; 
			} else {
				Get();
			}
		}
		if (la.kind == 2) {
			Get();
			expr = new IntLit(Integer.parseInt(t.val) * sign, t.line);      
		} else if (la.kind == 3) {
			Get();
			expr = new FloatLit(Float.parseFloat(t.val) * sign, t.line);    
		} else SynErr(68);
		return expr;
	}

	void MusicArgs(ArgList args) {
		Arg arg1 = MusicArg();
		if (arg1 != null) args.add(arg1); 
		while (la.kind == 48) {
			Get();
			Arg arg2 = MusicArg();
			if (arg2 != null) args.add(arg2); 
		}
	}

	Arg  MusicArg() {
		Arg  arg;
		arg = null; 
		if (StartOf(7)) {
			Expr expr = Num();
			arg = new Arg(new Ident("gain", t.line), expr); 
		} else if (la.kind == 1) {
			Get();
			Ident ident = new Ident(t.val, t.line); Expr expr = new BoolLit(true, t.line); 
			if (la.kind == 7) {
				Get();
				expr = null; 
				if (StartOf(8)) {
					expr = Const();
				} else if (la.kind == 18) {
					Get();
					expr = Expr();
					Expect(19);
				} else SynErr(69);
			}
			arg = new Arg(ident, expr); 
		} else SynErr(70);
		return arg;
	}



	public Config Parse(InputStream inputStream, ArrayList<Message> errors) {
		this.scanner = new Scanner(inputStream);
		this.errors = new Errors(errors);

		la = new Token();
		la.val = "";
		Get();
		File();
		Expect(0);

		scanner.buffer.Close();
		return mainNode;
	}

	private static final boolean[][] set = {
		{_T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _T,_T,_T,_T, _T,_T,_T,_T, _T,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_T, _x,_x,_x,_T, _T,_T,_x,_x, _T,_x,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_T,_T,_T, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _x,_x,_x,_T, _T,_x,_x,_T, _T,_T,_T,_x, _x,_T,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _T,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _T,_T,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_T,_T,_T, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _x,_x,_x,_x, _T,_x,_x,_T, _T,_T,_T,_x, _x,_T,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x},
		{_x,_x,_T,_T, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_T,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x}

	};
} // end Parser

class Errors {
	ArrayList<Message> errors;

    public Errors(ArrayList<Message> errors) {
        this.errors = errors;
    }

	public void SynErr (int line, int col, int n) {
        String s;
        switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "IDENT expected"; break;
			case 2: s = "INT expected"; break;
			case 3: s = "FLOAT expected"; break;
			case 4: s = "STRING expected"; break;
			case 5: s = "\"serve_playlists\" expected"; break;
			case 6: s = "\":\" expected"; break;
			case 7: s = "\"=\" expected"; break;
			case 8: s = "\";\" expected"; break;
			case 9: s = "\"group\" expected"; break;
			case 10: s = "\"end\" expected"; break;
			case 11: s = "\"play\" expected"; break;
			case 12: s = "\"instant\" expected"; break;
			case 13: s = "\"ifdef\" expected"; break;
			case 14: s = "\"priority\" expected"; break;
			case 15: s = "\"use_vanilla_player\" expected"; break;
			case 16: s = "\"begin\" expected"; break;
			case 17: s = "\"when\" expected"; break;
			case 18: s = "\"(\" expected"; break;
			case 19: s = "\")\" expected"; break;
			case 20: s = "\"let\" expected"; break;
			case 21: s = "\"in\" expected"; break;
			case 22: s = "\"default\" expected"; break;
			case 23: s = "\"interrupt\" expected"; break;
			case 24: s = "\"&&\" expected"; break;
			case 25: s = "\"||\" expected"; break;
			case 26: s = "\"==\" expected"; break;
			case 27: s = "\"~~\" expected"; break;
			case 28: s = "\"*~\" expected"; break;
			case 29: s = "\"!=\" expected"; break;
			case 30: s = "\"<\" expected"; break;
			case 31: s = "\">\" expected"; break;
			case 32: s = "\"<=\" expected"; break;
			case 33: s = "\">=\" expected"; break;
			case 34: s = "\"+\" expected"; break;
			case 35: s = "\"-\" expected"; break;
			case 36: s = "\"*\" expected"; break;
			case 37: s = "\"/\" expected"; break;
			case 38: s = "\"++\" expected"; break;
			case 39: s = "\"!\" expected"; break;
			case 40: s = "\"[\" expected"; break;
			case 41: s = "\"]\" expected"; break;
			case 42: s = "\".\" expected"; break;
			case 43: s = "\"@\" expected"; break;
			case 44: s = "\"$\" expected"; break;
			case 45: s = "\"any\" expected"; break;
			case 46: s = "\"all\" expected"; break;
			case 47: s = "\"has\" expected"; break;
			case 48: s = "\",\" expected"; break;
			case 49: s = "\"undefined\" expected"; break;
			case 50: s = "\"true\" expected"; break;
			case 51: s = "\"false\" expected"; break;
			case 52: s = "\"bool\" expected"; break;
			case 53: s = "\"int\" expected"; break;
			case 54: s = "\"float\" expected"; break;
			case 55: s = "\"string\" expected"; break;
			case 56: s = "\"area\" expected"; break;
			case 57: s = "\"combatant\" expected"; break;
			case 58: s = "\"playlist\" expected"; break;
			case 59: s = "\"list\" expected"; break;
			case 60: s = "\"map\" expected"; break;
			case 61: s = "??? expected"; break;
			case 62: s = "invalid ServerPlaylists"; break;
			case 63: s = "invalid Shed"; break;
			case 64: s = "invalid Type"; break;
			case 65: s = "invalid ExprPre"; break;
			case 66: s = "invalid ExprTerm"; break;
			case 67: s = "invalid Const"; break;
			case 68: s = "invalid Num"; break;
			case 69: s = "invalid MusicArg"; break;
			case 70: s = "invalid MusicArg"; break;
            default: s = "error " + n; break;
        }
        errors.add(new SynError(line, col, s));
    }
} // Errors
