package me.molybdenum.ambience_mini.engine.loader.syntactic_analysis;

import me.molybdenum.ambience_mini.engine.loader.abstract_syntax.expr.*;
import me.molybdenum.ambience_mini.engine.loader.abstract_syntax.conf.*;
import me.molybdenum.ambience_mini.engine.loader.abstract_syntax.shed.*;
import me.molybdenum.ambience_mini.engine.loader.abstract_syntax.play.*;
import java.util.ArrayList;

/* The required start of a Coco/R grammar file. "Program" specifies the starting symbol of the grammar. */


import org.slf4j.Logger;

public class Parser {
	public static final int _EOF = 0;
	public static final int _IDENT = 1;
	public static final int _INT = 2;
	public static final int _FLOAT = 3;
	public static final int _STRING = 4;
	public static final int maxT = 32;

	static final boolean _T = true;
	static final boolean _x = false;
	static final int minErrDist = 2;

	public Token t;    // last recognized token
	public Token la;   // lookahead token
	int errDist = minErrDist;
	
	public Scanner scanner;
	public Logger logger;
	public Errors errors;

	public Conf mainNode = null; // This contains the AST generated by calling parser.Parse().

    public boolean hasErrors() {
        return errors.count > 0;
    }

    private static String removeFirstAndLast(String str) {
        return str.substring(1, str.length() - 1);
    }

/*------------------------------------------------------------------------*/
/* The following section contains the token specification of Dims.*/


	public Parser(Scanner scanner, Logger logger) {
		this.scanner = scanner;
		this.logger = logger;
		errors = new Errors(logger);
	}

	void SynErr (int n) {
		if (errDist >= minErrDist) errors.SynErr(la.line, la.col, n);
		errDist = 0;
	}

	public void SemErr (String msg) {
		if (errDist >= minErrDist) errors.SemErr(t.line, t.col, msg);
		errDist = 0;
	}
	
	void Get () {
		for (;;) {
			t = la;
			la = scanner.Scan();
			if (la.kind <= maxT) {
				++errDist;
				break;
			}

			la = t;
		}
	}
	
	void Expect (int n) {
		if (la.kind==n) Get(); else { SynErr(n); }
	}
	
	boolean StartOf (int s) {
		return set[s][la.kind];
	}
	
	void ExpectWeak (int n, int follow) {
		if (la.kind == n) Get();
		else {
			SynErr(n);
			while (!StartOf(follow)) Get();
		}
	}
	
	boolean WeakSeparator (int n, int syFol, int repFol) {
		int kind = la.kind;
		if (kind == n) { Get(); return true; }
		else if (StartOf(repFol)) return false;
		else {
			SynErr(n);
			while (!(set[syFol][kind] || set[repFol][kind] || set[0][kind])) {
				Get();
				kind = la.kind;
			}
			return StartOf(syFol);
		}
	}
	
	void File() {
		mainNode = Conf();
	}

	Conf  Conf() {
		Conf  conf;
		conf = null; 
		if (la.kind == 5) {
			Get();
			Expect(1);
			IdentP ident = new IdentP(t.val); 
			Expect(6);
			PL play = Play();
			Expect(7);
			Conf inner = Conf();
			conf = new Playlist(ident, play, inner); 
		} else if (StartOf(1)) {
			Shed shed = Shed();
			conf = new Schedule(shed); 
		} else SynErr(33);
		return conf;
	}

	PL  Play() {
		PL  play;
		play = PlayTerm();
		while (la.kind == 8) {
			Get();
			PL play2 = PlayTerm();
			play = new Concat(play, play2); 
		}
		return play;
	}

	Shed  Shed() {
		Shed  shed;
		shed = null; boolean instant = false; 
		if (la.kind == 15) {
			Get();
			if (la.kind == 16) {
				Get();
				instant = true; 
			}
			PL pl = Play();
			Expect(7);
			shed = new Play(pl, instant); 
		} else if (la.kind == 17) {
			Get();
			ArrayList<Shed> items = new ArrayList<>();  
			while (StartOf(1)) {
				Shed shed2 = Shed();
				items.add(shed2); 
			}
			Expect(18);
			shed = new Block(items); 
		} else if (la.kind == 19) {
			Get();
			Expect(20);
			Expr expr = Expr();
			Expect(21);
			Shed shed2 = Shed();
			shed = new When(expr, shed2); 
		} else if (la.kind == 22) {
			Get();
			Shed shed2 = Shed();
			shed = new When(new BoolV(true), shed2); 
		} else if (la.kind == 23) {
			Get();
			Shed shed2 = Shed();
			shed = new Interrupt(shed2); 
		} else SynErr(34);
		return shed;
	}

	PL  PlayTerm() {
		PL  play;
		play = new Nil(); FloatV gain = null; 
		if (la.kind == 9) {
			Get();
			if (StartOf(2)) {
				PL load = PlayTerm();
				play = load;      
				while (la.kind == 10) {
					Get();
					load = PlayTerm();
					play = new Concat(play, load); 
				}
			}
			Expect(11);
		} else if (la.kind == 1) {
			Get();
			play = new IdentP(t.val); 
		} else if (la.kind == 12) {
			Get();
		} else if (la.kind == 4) {
			Get();
			StringV file = new StringV(removeFirstAndLast(t.val)); 
			if (la.kind == 13) {
				Get();
				if (la.kind == 3) {
					Get();
				} else if (la.kind == 2) {
					Get();
				} else SynErr(35);
				gain = new FloatV(Float.parseFloat(t.val));            
				Expect(14);
			}
			play = new Load(file, gain);                           
		} else SynErr(36);
		return play;
	}

	Expr  Expr() {
		Expr  expr;
		BinaryOperators op = BinaryOperators.AND; 
		expr = ExprEq();
		while (la.kind == 24 || la.kind == 25) {
			if (la.kind == 24) {
				Get();
				op = BinaryOperators.AND; 
			} else {
				Get();
				op = BinaryOperators.OR; 
			}
			Expr expr2 = ExprEq();
			expr = new BinaryOp(op, expr, expr2); 
		}
		return expr;
	}

	Expr  ExprEq() {
		Expr  expr;
		BinaryOperators op = BinaryOperators.EQ; 
		expr = ExprTerm();
		while (la.kind == 26 || la.kind == 27) {
			if (la.kind == 26) {
				Get();
				op = BinaryOperators.EQ; 
			} else {
				Get();
				op = BinaryOperators.APP_EQ; 
			}
			Expr expr2 = ExprTerm();
			expr = new BinaryOp(op, expr, expr2); 
		}
		return expr;
	}

	Expr  ExprTerm() {
		Expr  expr;
		expr = null;                                   
		switch (la.kind) {
		case 1: {
			Get();
			expr = new IdentE(t.val);                      
			break;
		}
		case 2: {
			Get();
			expr = new IntV(Integer.parseInt(t.val));      
			break;
		}
		case 3: {
			Get();
			expr = new FloatV(Float.parseFloat(t.val));    
			break;
		}
		case 4: {
			Get();
			expr = new StringV(removeFirstAndLast(t.val)); 
			break;
		}
		case 28: {
			Get();
			expr = new BoolV(true);                        
			break;
		}
		case 29: {
			Get();
			expr = new BoolV(false);                       
			break;
		}
		case 30: {
			Get();
			Expect(1);
			expr = new Ev(new IdentE(t.val));              
			break;
		}
		case 31: {
			Get();
			Expect(1);
			expr = new Get(new IdentE(t.val));             
			break;
		}
		case 20: {
			Get();
			expr = Expr();
			Expect(21);
			break;
		}
		default: SynErr(37); break;
		}
		return expr;
	}



	public void Parse() {
		la = new Token();
		la.val = "";		
		Get();
		File();
		Expect(0);

		scanner.buffer.Close();
	}

	private static final boolean[][] set = {
		{_T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_T, _x,_T,_x,_T, _x,_x,_T,_T, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x},
		{_x,_T,_x,_x, _T,_x,_x,_x, _x,_T,_x,_x, _T,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x,_x,_x, _x,_x}

	};
} // end Parser


class Errors {
	public Logger logger;

	public int count = 0;                                     // number of errors detected
	public String errMsgFormat = "-- line {0} col {1}: {2}"; // 0=line, 1=column, 2=text

    public Errors(Logger logger) {
        this.logger = logger;
    }
	
	protected void printMsg(int line, int column, String msg) {
		StringBuffer b = new StringBuffer(errMsgFormat);
		int pos = b.indexOf("{0}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, line); }
		pos = b.indexOf("{1}");
		if (pos >= 0) { b.delete(pos, pos+3); b.insert(pos, column); }
		pos = b.indexOf("{2}");
		if (pos >= 0) b.replace(pos, pos+3, msg);
		logger.error(b.toString());
	}
	
	public void SynErr (int line, int col, int n) {
		String s;
		switch (n) {
			case 0: s = "EOF expected"; break;
			case 1: s = "IDENT expected"; break;
			case 2: s = "INT expected"; break;
			case 3: s = "FLOAT expected"; break;
			case 4: s = "STRING expected"; break;
			case 5: s = "\"playlist\" expected"; break;
			case 6: s = "\"=\" expected"; break;
			case 7: s = "\";\" expected"; break;
			case 8: s = "\"++\" expected"; break;
			case 9: s = "\"[\" expected"; break;
			case 10: s = "\",\" expected"; break;
			case 11: s = "\"]\" expected"; break;
			case 12: s = "\"NIL\" expected"; break;
			case 13: s = "\"<\" expected"; break;
			case 14: s = "\">\" expected"; break;
			case 15: s = "\"play\" expected"; break;
			case 16: s = "\"instant\" expected"; break;
			case 17: s = "\"begin\" expected"; break;
			case 18: s = "\"end\" expected"; break;
			case 19: s = "\"when\" expected"; break;
			case 20: s = "\"(\" expected"; break;
			case 21: s = "\")\" expected"; break;
			case 22: s = "\"default\" expected"; break;
			case 23: s = "\"interrupt\" expected"; break;
			case 24: s = "\"&&\" expected"; break;
			case 25: s = "\"||\" expected"; break;
			case 26: s = "\"==\" expected"; break;
			case 27: s = "\"~~\" expected"; break;
			case 28: s = "\"true\" expected"; break;
			case 29: s = "\"false\" expected"; break;
			case 30: s = "\"@\" expected"; break;
			case 31: s = "\"$\" expected"; break;
			case 32: s = "??? expected"; break;
			case 33: s = "invalid Conf"; break;
			case 34: s = "invalid Shed"; break;
			case 35: s = "invalid PlayTerm"; break;
			case 36: s = "invalid PlayTerm"; break;
			case 37: s = "invalid ExprTerm"; break;
			default: s = "error " + n; break;
		}
		printMsg(line, col, s);
		count++;
	}

	public void SemErr (int line, int col, String s) {	
		printMsg(line, col, s);
		count++;
	}
	
	public void SemErr (String s) {
		logger.error(s);
		count++;
	}
	
	public void Warning (int line, int col, String s) {	
		printMsg(line, col, s);
	}
	
	public void Warning (String s) {
		logger.error(s);
	}
} // Errors


class FatalError extends RuntimeException {
	public static final long serialVersionUID = 1L;
	public FatalError(String s) { super(s); }
}
